openapi: 3.0.0
info:
  title: Messages API
  version: 1.0.0
paths:
  /messages:
    get:
      summary: Get Messages
      description: Retrieves a list of messages.
      parameters:
        - name: status
          in: query
          description: Filter messages by status
          required: false
          schema:
            type: "string"
            enum:
              - "pending"
              - "sent"
              - "failed"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  messages:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        uuid: 
                          type: "string"
                        text:
                          type: "string"
                        status:
                          type: "string"
                          enum:
                            - "pending"
                            - "sent"
                            - "failed"
              example:
                messages:
                  - uuid: "uuid-1"
                    text: "hello"
                    status: "pending"
                  - uuid: "uuid-2"
                    text: "how are you"
                    status: "sent"
                  - uuid: "uuid-2"
                    text: "i'm fine thx"
                    status: "failed"
                  

  /messages/send:
    post:
      summary: Send a Message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: "hello"
              required:
                - text
      responses:
        '201':
          description: Message created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 3595
                  uuid:
                    type: string
                    format: uuid
                    example: "1f08477a-1e3a-6dc0-b8fc-97323204e66d"
                  text:
                    type: string
                    example: "hello"
                  status:
                    type: string
                    enum: [pending, sent, failed]
                    example: "pending"
                  createdAt:
                    type: string
                    format: date-time
                    example: "2025-08-29T01:29:40+00:00"
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Text is required"
